name: Publish Release

on:
  release:
    types: [created]

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: "1.1.14"

      - name: Build package with poetry
        run: poetry build

      - name: Publish to PyPi
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
