name: PythonTests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      uses: abatilo/actions-poetry@1.0.3
      with:
        args: "install"
    - name: Run tests
      uses: abatilo/actions-poetry@1.0.3
      with:
        args: "run pytest"
