name: Tests

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        token: ${{ secrets.GIT_TOKEN }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: 0.12.17
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run invoke test
    - name: Run style checker
      run: poetry run flake8
